### ISSUE TITLE
IP / hostname to put when registering a device

### ISSUE THREAD

**Issue by wmfairuz** [wso2/emm-agent-android#4]
Hi,

I access my EMM using https://192.168.100.162:9443/emm

When registering a device using the agent, I put 192.168.100.162 but while registering, the agent throws "Server is unavailable". What should I put as the address when registering a device?

These are information from adblog

V/ServerUtils(19824): emm.mycorpcloud.bizPosting '{username=theadmin, password=theadmin}' to http://192.168.100.162:9443/emm/api/devices/clientkey
V/ServerUtils(19824): Posting 'username=theadmin&password=theadmin' to http://192.168.100.162:9443/emm/api/devices/clientkey

**Comment by menasheu** [comment]
I had a similar problem but in your  case you should first write the correct address i.e. 192.168.100.162 with the periods.

**Comment by kasundananjaya** [comment]
In your agent code in CommonUtilities.java, can you check the port is 9443 (https)? If so you need to generate a BKS file to work with SSL by using your server SSL certificate and put it inside android agent. Steps described in [1].

[1] - https://docs.wso2.com/display/EMM110/Android+Configurations

**Comment by xin4428** [comment]
Hello! Who has the Android source of WSO2 EMM Agent 2.0 APK ?。Can you sent the source to my email ?xin2840830311@gmail.com
   thank you

**Comment by milanperera** [comment]
Source can be found in https://github.com/wso2/product-emm/tree/master/modules/mobile-agents/android/client

**Comment by Sejushi** [comment]
I can't download this.

**Comment by kasundananjaya** [comment]
Since the client source in product-emm repo, you have to clone the entire repository, https://github.com/wso2/product-emm.
